function msg1()
{
	document.getElementById("switch").innerHTML="<center style='color:black;font-size:200%;'>过去24小时水环境质量指标数值表</center><center><table border='1' style='margin-left:30px;color:black;font-size:150%'>"+
			"<tr><th></th>"+
			"<td>溶解氧(mg/L)</td>"+
			"<td>高锰酸钾浓度(mg/L)</td>"+
		    "<td>氨氮浓度(mg/L)</td>"+
		    "<td>总磷浓度(mg/L)</td>"+
		    "<td>工业污水量(m³)</td>"+
		    "<td>农业污水量(m³)</td>"+
		    "<tr><td>过去24小时水环境质量</td>"+
			"<td>56</td>"+
			"<td>48</td>"+
		    "<td>111</td>"+
		    "<td>78</td>"+
		    "<td>32</td>"+
		    "<td>60</td></tr>"+
		    "<tr><td>水环境质量</td>"+
			"<td>优</td>"+
			"<td>良</td>"+
		    "<td>轻度污染</td>"+
		    "<td>良</td>"+
		    "<td>优</td>"+
		    "<td>良</td></tr>"+
		    "</table></center>";
}
function msg2()
{
	document.getElementById("switch").innerHTML="<center style='color:black;font-size:200%;'>实时水环境质量指标数值表</center><center><table border='1' style='margin-left:30px;color:black;font-size:150%'>"+
			"<tr><td></td>"+
			"<td>溶解氧(mg/L)</td>"+
			"<td>高锰酸钾浓度(mg/L)</td>"+
		    "<td>氨氮浓度(mg/L)</td>"+
		    "<td>总磷浓度(mg/L)</td>"+
		    "<td>工业污水量(m³)</td>"+
		    "<td>农业污水量(m³)</td>"+
		    "<tr><td>实时水环境质量指数</td>"+
			"<td>98</td>"+
			"<td>30</td>"+
		    "<td>60</td>"+
		    "<td>48</td>"+
		    "<td>32</td>"+
		    "<td>160</td></tr>"+
		    "<tr><td>空气质量</td>"+
			"<td>优</td>"+
			"<td>良</td>"+
		    "<td>良</td>"+
		    "<td>优</td>"+
		    "<td>优</td>"+
		    "<td>重度污染</td></tr>"+
		    "</table></center>";
}
function msg3()
{
	document.getElementById("switch").innerHTML="<center style='color:black;font-size:200%'>未来24小时水环境质量指标数值表</center><center><table border='1' style='margin-left:30px;color:black;font-size:150%'>"+
			"<tr><th></th>"+
			"<td>溶解氧(mg/L)</td>"+
			"<td>高锰酸钾浓度(mg/L)</td>"+
		    "<td>氨氮浓度(mg/L)</td>"+
		    "<td>总磷浓度(mg/L)</td>"+
		    "<td>工业污水量(m³)</td>"+
		    "<td>农业污水量(m³)</td></tr>"+
		    "<tr><td>未来24小时水环境质量</td>"+
			"<td>89</td>"+
			"<td>48</td>"+
		    "<td>148</td>"+
		    "<td>112</td>"+
		    "<td>16</td>"+
		    "<td>120</td></tr>"+
		    "<tr><td>水环境质量</td>"+
			"<td>优</td>"+
			"<td>良</td>"+
		    "<td>轻度污染</td>"+
		    "<td>轻度污染</td>"+
		    "<td>优</td>"+
		    "<td>轻度污染</td></tr>"+
		    "</table></center>";
}