function msg1()
{
	document.getElementById("switch").innerHTML="<center style='color:black;font-size:300%;font-weight:bold'>过去24小时水环境质量指标数值表</center><center><table border='1' style='margin-left:30px;color:black;font-size:150%'>"+
			"<tr><th></th>"+
			"<th>溶解氧(mg/L)</th>"+
			"<th>高锰酸钾浓度(mg/L)</th>"+
		    "<th>氨氮浓度(mg/L)</th>"+
		    "<th>总磷浓度(mg/L)</th>"+
		    "<th>工业污水量(m³)</th>"+
		    "<th>农业污水量(m³)</th>"+
		    "<tr><th>过去24小时水环境质量指数</th>"+
			"<td>56</td>"+
			"<td>48</td>"+
		    "<td>111</td>"+
		    "<td>78</td>"+
		    "<td>32</td>"+
		    "<td>60</td></tr>"+
		    "<tr><th>水环境质量</th>"+
			"<td>优</td>"+
			"<td>良</td>"+
		    "<td>轻度污染</td>"+
		    "<td>良</td>"+
		    "<td>优</td>"+
		    "<td>良</td></tr>"+
		    "</table></center>";
}
function msg2()
{
	document.getElementById("switch").innerHTML="<center style='color:black;font-size:300%;font-weight:bold'>实时水环境质量指标数值表</center><center><table border='1' style='margin-left:30px;color:black;font-size:150%'>"+
			"<tr><th></th>"+
			"<th>溶解氧(mg/L)</th>"+
			"<th>高锰酸钾浓度(mg/L)</th>"+
		    "<th>氨氮浓度(mg/L)</th>"+
		    "<th>总磷浓度(mg/L)</th>"+
		    "<th>工业污水量(m³)</th>"+
		    "<th>农业污水量(m³)</th>"+
		    "<tr><th>实时水环境质量指数</th>"+
			"<td>98</td>"+
			"<td>30</td>"+
		    "<td>60</td>"+
		    "<td>48</td>"+
		    "<td>32</td>"+
		    "<td>160</td></tr>"+
		    "<tr><th>空气质量</th>"+
			"<td>优</td>"+
			"<td>良</td>"+
		    "<td>良</td>"+
		    "<td>优</td>"+
		    "<td>优</td>"+
		    "<td>重度污染</td></tr>"+
		    "</table></center>";
}
function msg3()
{
	document.getElementById("switch").innerHTML="<center style='color:black;font-size:300%;font-weight:bold'>未来24小时水环境质量指标数值表</center><center><table border='1' style='margin-left:30px;color:black;font-size:150%'>"+
			"<tr><th></th>"+
			"<th>溶解氧(mg/L)</th>"+
			"<th>高锰酸钾浓度(mg/L)</th>"+
		    "<th>氨氮浓度(mg/L)</th>"+
		    "<th>总磷浓度(mg/L)</th>"+
		    "<th>工业污水量(m³)</th>"+
		    "<th>农业污水量(m³)</th></tr>"+
		    "<tr><th>未来24小时水环境质量指数</th>"+
			"<td>89</td>"+
			"<td>48</td>"+
		    "<td>148</td>"+
		    "<td>112</td>"+
		    "<td>16</td>"+
		    "<td>120</td></tr>"+
		    "<tr><th>水环境质量</th>"+
			"<td>优</td>"+
			"<td>良</td>"+
		    "<td>轻度污染</td>"+
		    "<td>轻度污染</td>"+
		    "<td>优</td>"+
		    "<td>轻度污染</td></tr>"+
		    "</table></center>";
}